def draw_library():
    print("      /\\")
    print("     /  \\")
    print("    /    \\")
    print("   /      \\")
    print("  /        \\")
    print(" /          \\")
    print("/            \\")
    print("|````````````|")
    print("|  /\    /\  |")
    print("|  \/    \/  |")
    print("|            |")
    print("|     __     |")
    print("|    /  \    |")
    print("|   |    |   |")
    print("|   |-   |   |")
    print("|___|____|___|")
    return