def draw_school():
    print("      /\\           /\\")
    print("     /  \\         /  \\")
    print("    /    \\       /    \\")
    print("   /      \\     /      \\")
    print("  /        \\   /        \\")
    print(" /          \\ /          \\")
    print("/                        \\")
    print("|````````````````````````|")
    print("|  /\    /\    /\    /\  |")
    print("|  \/    \/    \/    \/  |")
    print("|                        |")
    print("|     __          __     |")
    print("|    /  \        /  \    |")
    print("|   |    |      |    |   |")
    print("|   |-   |      |-   |   |")
    print("|___|____|______|____|___|")
    return
